### ISSUE TITLE
#macro里面定义变量好像不会从json里面拿数据

### ISSUE THREAD

**Issue by fmoon** [richard-chen-1985/gulp-velocityjs#2]

**Comment by richardchen85** [comment]
场景是什么呢

**Comment by fmoon** [comment]
修改下问题
有一个common.vm里面有变量$abc
index.vm里#parse(common.vm)
但是$abc这个变量的值读取的是 index.json里面的
希望从common.json里面取数据
因为会有多个页面vm引用这个common.vm

**Comment by richardchen85** [comment]
数据源的读取顺序是，当前页面的.json文件=》页面引入文件的.json文件，所以应该是不会存在你说的那种情况耶 @fmoon

**Comment by fmoon** [comment]
我错了~  vm目录跟json的目录木有对应~  打搅啦(>_<)
